rbenv:
  env: system
  version: v0.4.0
  ruby_version: 2.1.5
timezone: Asia/Tokyo
wordpress_installs:
  - name: wordpress
    dbname: wp_development
    dbuser: wpuser
    dbpass: wppass
    dbhost: localhost
    path: /var/www/html
    admin_name: admin
    admin_email: root@localhost.localdomain
    admin_password: 'xuFr8=aPra@a'
    title: pet video
    url: http://dev01.tnky.pw
    themes: []
    plugins: []
    users: {}
cms_domain: dev01.tnky.pw
aws:
  access: AKIAIHFGVZ2JKA5AIT3Q
  secret: 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
db_user: wpuser
db_password: wppass
db_name: wp_development
db_my_cnf: ../files/my.cnf
db_charset_cnf: ../files/charset.cnf.dev
apache2_conf: ../files/000-default.conf
lsyncd_conf: ../files/lsyncd.conf.lua
lsyncd_target: s3://wp.tnky.pw
s3cmd_conf: ../files/s3cmd.conf
aws_conf: ../files/aws.conf
