rbenv:
  env: system
  version: v0.4.0
  ruby_version: 2.1.5
timezone: Asia/Tokyo
wordpress_installs:
  - name: wordpress
    dbname: wp_production
    dbuser: mediacommerce
    dbpass: 3bAigaeshi!
    dbhost: localhost
    path: /var/www/html
    admin_name: pets-video
    admin_email: root@localhost.localdomain
    admin_password: 'TxUnFr8=aPra@anS!'
    title: pets video
    url: http://cms.pets-video.com
    themes: []
    plugins: []
    users: {}
cms_domain: cms.pets-video.com
aws:
  access: AKIAJMHGUCVGNMXOMXRA
  secret: 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
db_user: mediacommerce
db_password: 3bAigaeshi!
db_name: wp_production
db_my_cnf: ../files/my.cnf
db_charset_cnf: ../files/charset.cnf.dev
apache2_conf: ../files/000-default.conf
lsyncd_conf: ../files/lsyncd.conf.lua
lsyncd_target: s3://www.pets-video.com
s3cmd_conf: ../files/s3cmd.conf
aws_conf: ../files/aws.conf
