- hosts: staging
  sudo: true
  vars:
    rbenv:
      env: system
      version: v0.4.0
      ruby_version: 2.1.5
    timezone: Asia/Tokyo
    db_user: bang_w
    db_password: bang_w_password
    db_name: bang_staging
    db_my_cnf: ../files/my.cnf
    db_charset_cnf: ../files/charset.cnf.dev
  roles:
    - users
    - apt-db
    - rbenv
    - apt-web
